<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SocialGoal.Data</AssemblyName>
    <OutputType>Library</OutputType>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SocialGoal.Data</RootNamespace>
    <SolutionDir>..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Include="App.config"></None>
    <None Include="packages.config"></None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PagedList.Mvc" Version="4.5.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.4"></PackageReference>
    <PackageReference Include="PagedList.NET" Version="1.0.0"></PackageReference>
    <PackageReference Include="EntityFramework" Version="6.5.1"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SocialGoal.Model/SocialGoal.Model.csproj"></ProjectReference>
  </ItemGroup>
</Project>