<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SocialGoal.Web.Core</AssemblyName>
    <OutputType>Library</OutputType>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SocialGoal.Web.Core</RootNamespace>
    <SolutionDir>..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"></FrameworkReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config"></None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.Abstractions" Version="2.0.0"></PackageReference>
    <PackageReference Include="PagedList.Core" Version="1.17.4"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0"></PackageReference>
    <PackageReference Include="AutoMapper" Version="13.0.1"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SocialGoal.Core/SocialGoal.Core.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Model/SocialGoal.Model.csproj"></ProjectReference>
  </ItemGroup>
</Project>