<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>SocialGoal</AssemblyName>
    <OutputType>Exe</OutputType>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SocialGoal</RootNamespace>
    <SolutionDir>..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Scripts\jquery-1.6.2-vsdoc.js"></None>
    <None Include="Scripts\jquery-1.7.1-vsdoc.js"></None>
    <None Include="Scripts\jquery.validate-vsdoc.js"></None>
    <None Include="Scripts\_references.js"></None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="App_Data\"></Folder>
    <Folder Include="Scripts\FunctionScripts\"></Folder>
  </ItemGroup>
  <ItemGroup>
    <None Include="Project_Readme.html"></None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.4"></PackageReference>
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.2.1"></PackageReference>
    <PackageReference Include="X.PagedList" Version="10.2.1"></PackageReference>
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8"></PackageReference>
    <PackageReference Include="ElmahCore" Version="2.1.2"></PackageReference>
    <PackageReference Include="ElmahCore.Mvc" Version="1.2.5"></PackageReference>
    <PackageReference Include="MvcMailer" Version="4.5.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Owin" Version="8.0.13"></PackageReference>
    <PackageReference Include="Microsoft.Owin.Security.MicrosoftAccount" Version="2.0.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNet.Identity.Owin" Version="1.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Owin.Security.Twitter" Version="2.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Owin.Security.Facebook" Version="2.0.0"></PackageReference>
    <PackageReference Include="T4Scaffolding.Core" Version="1.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Owin.Security.Google" Version="2.0.0"></PackageReference>
    <PackageReference Include="bootstrap" Version="5.3.1"></PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3"></PackageReference>
    <PackageReference Include="jQuery.Validation" Version="1.19.5"></PackageReference>
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="4.0.0"></PackageReference>
    <PackageReference Include="Modernizr" Version="2.8.3"></PackageReference>
    <PackageReference Include="Respond" Version="1.4.2"></PackageReference>
    <PackageReference Include="jQuery" Version="3.7.0"></PackageReference>
    <PackageReference Include="Autofac" Version="8.1.0"></PackageReference>
    <PackageReference Include="EntityFramework" Version="6.5.1"></PackageReference>
    <PackageReference Include="AutoMapper" Version="13.0.1"></PackageReference>
    <PackageReference Include="System.Resources.Extensions" Version="*"></PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SocialGoal.Core/SocialGoal.Core.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Model/SocialGoal.Model.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Data/SocialGoal.Data.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Web.Core/SocialGoal.Web.Core.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Service/SocialGoal.Service.csproj"></ProjectReference>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}"></FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
</Project>