<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SocialGoal.Service</AssemblyName>
    <OutputType>Library</OutputType>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SocialGoal.Service</RootNamespace>
    <SolutionDir>..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SocialGoal.Core/SocialGoal.Core.csproj" />
    <ProjectReference Include="../SocialGoal.Model/SocialGoal.Model.csproj" />
    <ProjectReference Include="../SocialGoal.Data/SocialGoal.Data.csproj" />
    <ProjectReference Include="../SocialGoal.Web.Core/SocialGoal.Web.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
</Project>