<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SocialGoal.Tests</AssemblyName>
    <OutputType>Library</OutputType>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SocialGoal.Tests</RootNamespace>
    <SolutionDir>..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"></FrameworkReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config"></None>
    <None Include="packages.config">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}"></Service>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" Version="2.3.0"></PackageReference>
    <PackageReference Include="System.Security.Claims" Version="4.3.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.Abstractions" Version="2.0.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.2"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.0"></PackageReference>
    <PackageReference Include="MSTest.TestAdapter" Version="3.7.3"></PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"></PackageReference>
    <PackageReference Include="Moq" Version="4.20.72"></PackageReference>
    <PackageReference Include="MSTest.TestFramework" Version="3.8.0"></PackageReference>
    <PackageReference Include="NUnit" Version="*"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.4"></PackageReference>
    <PackageReference Include="T4Scaffolding.Core" Version="1.0.0"></PackageReference>
    <PackageReference Include="EntityFramework" Version="6.5.1"></PackageReference>
    <PackageReference Include="AutoMapper" Version="13.0.1"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SocialGoal.Model/SocialGoal.Model.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Data/SocialGoal.Data.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Web.Core/SocialGoal.Web.Core.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal.Service/SocialGoal.Service.csproj"></ProjectReference>
    <ProjectReference Include="../SocialGoal/SocialGoal.Web.csproj"></ProjectReference>
  </ItemGroup>
</Project>